# Logistic Regression

In [28]:
import os
os.chdir("C:\\datasciencepractice")

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline

# Read data of Telecommunication company

In [30]:
churn_df=pd.read_csv("ChurnData.csv")
churn_df.head(5)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [31]:
churn_df.columns

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')

In [32]:
churn_df.index

RangeIndex(start=0, stop=200, step=1)

# Preprocessing

In [33]:
churn_df=churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
churn_df["churn"]=churn_df["churn"].astype("int")
churn_df[0:5]

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  
0      1  
1      1  
2      0  
3      0  
4      0

In [34]:
print("Shape of Data",churn_df.shape)
print("Columns in Data Set",churn_df.columns)

Shape of Data (200, 10)
Columns in Data Set Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'churn'],
      dtype='object')


In [35]:
x=np.asarray(churn_df[["tenure","age","address","income","ed","employ","equip","callcard","wireless"]])
x[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.,   1.,   1.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.,   0.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.,   1.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.,   1.,   0.]])

In [36]:
y=np.asarray(churn_df["churn"])
y[0:5]

array([1, 1, 0, 0, 0])

In [37]:
from sklearn import preprocessing
x=preprocessing.StandardScaler().fit(x).transform(x)
x[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695,  0.64686916,  1.56469673],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695, -1.54590766, -0.63910148],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695, -1.54590766, -0.63910148],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ,  0.64686916,  1.56469673],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695,  0.64686916, -0.63910148]])

# Model

In [39]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=1/3,random_state=3)

In [40]:
print("Training Data Shape::",train_x.shape,train_y.shape)
print("Testing Data Shape::",test_x.shape,test_y.shape)

Training Data Shape:: (133, 9) (133,)
Testing Data Shape:: (67, 9) (67,)


In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR=LogisticRegression(C=0.01,solver='liblinear').fit(train_x,train_y)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [42]:
yhat=LR.predict(test_x)
yhat

array([1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1])

In [43]:
yhat_prob=LR.predict_proba(test_x)
yhat_prob

array([[0.39507159, 0.60492841],
       [0.51688445, 0.48311555],
       [0.52164111, 0.47835889],
       [0.55333769, 0.44666231],
       [0.44280585, 0.55719415],
       [0.49863113, 0.50136887],
       [0.6954562 , 0.3045438 ],
       [0.58954366, 0.41045634],
       [0.47794968, 0.52205032],
       [0.42116204, 0.57883796],
       [0.62408259, 0.37591741],
       [0.5198283 , 0.4801717 ],
       [0.38455721, 0.61544279],
       [0.71544307, 0.28455693],
       [0.42431587, 0.57568413],
       [0.50281308, 0.49718692],
       [0.48000333, 0.51999667],
       [0.48352539, 0.51647461],
       [0.67862398, 0.32137602],
       [0.39916919, 0.60083081],
       [0.46105467, 0.53894533],
       [0.53014928, 0.46985072],
       [0.6351626 , 0.3648374 ],
       [0.49293919, 0.50706081],
       [0.66015636, 0.33984364],
       [0.54697907, 0.45302093],
       [0.50991296, 0.49008704],
       [0.42336217, 0.57663783],
       [0.43111222, 0.56888778],
       [0.44184685, 0.55815315],
       [0.

# Evalution

In [44]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(test_y,yhat)

C:\Users\Shulabh Dixit\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.6865671641791045

In [45]:
from sklearn import metrics
print("Confusion Matrix::",metrics.confusion_matrix(test_y,yhat))

Confusion Matrix:: [[34 16]
 [ 5 12]]


In [46]:
print("claasification metrics::",metrics.classification_report(test_y,yhat))

claasification metrics::               precision    recall  f1-score   support

           0       0.87      0.68      0.76        50
           1       0.43      0.71      0.53        17

    accuracy                           0.69        67
   macro avg       0.65      0.69      0.65        67
weighted avg       0.76      0.69      0.71        67



In [47]:
from sklearn.metrics import log_loss
print("log loss ::",metrics.log_loss(test_y,yhat_prob))

log loss :: 0.5964010995117199
